# Generated by Django 2.2.15 on 2020-08-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_GoodsCategory_link_many_GoodsCategoryBrand', to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
    ]
